### ISSUE TITLE
Add compare attribute sets to REST service layer

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/owlsim-v3#32]
Compare two profiles, for example:
compare/{matcher}?referenceIDs=foo&referenceNegated=bar&queryIDs=baz...

**Comment by cmungall** [comment]
Example (follow instructions in README to start with this test database)

```
http://localhost:8080/api/match/phenodigm?id=http://x.org/bone-morphology&targetClassId=http://x.org/brain-size&targetClassId=http://x.org/inc-femur-length
```

**Comment by cmungall** [comment]
Note: negated target class Ids not done. Open if you want this done
