### ISSUE TITLE
Docker file / image for owlsim3 server

### ISSUE THREAD

**Issue by tudorgroza** [monarch-initiative/owlsim-v3#58]
Hi @jnguyenx - can you please hack a Dockerfile to build a configuration specific docker image? Can you also please point me to some documentation that shows how to build the associated data files (owl, tsvs, etc).
Thanks!

**Comment by jnguyenx** [comment]
I've set up some human only data for you. Currently our data pipeline is fragile and complicated but @cmungall is working on simplifying this process. If you can wait a bit it'll be easier to generate the files needed by owlsim.

So keep in mind that we'll temporary use this all-hp.owl until we have a better pipelin solution.

In the meantime, here's the command to build the docker image for human:
```
mvn package
docker build --build-arg species=human -t owlsim-human
docker run -p 8080:8080 owlsim-human
```

**Comment by jnguyenx** [comment]
Here's the issue to monitor for the simplified data provider:
https://github.com/biolink/biolink-api/issues/27
