### ISSUE TITLE
Command error in repository Readme

### ISSUE THREAD

**Issue by ManavalanG** [monarch-initiative/owlsim-v3#83]
The command to build docker just with human species data in [readme](https://github.com/monarch-initiative/owlsim-v3/blob/master/README.md) is missing period symbol in the end.

`docker build --build-arg species=human -t owlsim-human`
should be 
`docker build --build-arg species=human -t owlsim-human .`

**Comment by cmungall** [comment]
Looks like it was fixed here: https://github.com/monarch-initiative/owlsim-v3/commit/2f228dd2738c0d5f5ba35df207bb3110a7e346d8 sorry for not notifying you, thanks for the report!
